
package com.zhaodf.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpeakImpl", targetNamespace = "http://impl.zhaodf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpeakImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "speak", targetNamespace = "http://impl.zhaodf.com/", className = "com.zhaodf.impl.Speak")
    @ResponseWrapper(localName = "speakResponse", targetNamespace = "http://impl.zhaodf.com/", className = "com.zhaodf.impl.SpeakResponse")
    @Action(input = "http://impl.zhaodf.com/SpeakImpl/speakRequest", output = "http://impl.zhaodf.com/SpeakImpl/speakResponse")
    public String speak(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
